version: "3"

services:

  test:
    build:
      context: "../.."
      dockerfile: platform/local/Dockerfile
      target: test
    working_dir: /bats
    volumes:
      - "../../tests:/bats"
      - "../../source:/source"
      - "../../extras:/home/root/.extras"
    environment:
      ACTION_SOURCE_DIR: /source/rootfs
      GITHUB_TOKEN: $GITHUB_TOKEN
      EXTRAS_DIR: /home/root/.extras