version: "3"

services:

  test:
    build:
      context: "../.."
      dockerfile: platform/local/Dockerfile
      target: test
    working_dir: /bats
    volumes:
      - "../../tests:/bats"
      - "../../source/rootfs:/action"
      - "../../extras:/home/action/.extras"
    environment:
      ACTION_HOME_DIR: /action
      GITHUB_TOKEN: $GITHUB_TOKEN
      EXTRAS_DIR: /home/action/.extras
      # __DEBUG_MODE_ENABLED__: true